const actionTypes = {
  portfolio: {
    PORTFOLIO_FETCH: 'PORTFOLIO_FETCH',
    PORTFOLIO_FETCH_SUCCESS: 'PORTFOLIO_FETCH_SUCCESS',
  },
  constituent: {
    CONSTITUENT_FETCH: 'CONSTITUENT_FETCH',
    CONSTITUENT_FETCH_SUCCESS: 'CONSTITUENT_FETCH_SUCCESS',
    CONSTITUENT_WEIGHT_CHANGED: 'CONSTITUENT_WEIGHT_CHANGED',
    REBALANCE: 'REBALANCE',
    RESET: 'RESET',
    DELETE: 'DELETE',
    TOGGLE_LOCK: 'TOGGLE_LOCK',
  },
};

export default actionTypes;
